heat_template_version: 2014-10-16
description: A base Ubuntu xenial server
parameters:
  image_id:
    type: string
    description: >
      Ubuntu image
    default: ubuntu-xenial
 
resources:
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id}
      flavor: m1.small
      key_name: generic-cloud
      networks:
        - port: { get_resource: port }
 
  port:
    type: OS::Neutron::Port
    properties:
      network: pueblo
 
  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: external
 
  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: port }
